# This workflow will do build and test. Deploy to dev

name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run docs:build
      - run: ls docs/.vuepress/dist
      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.8
      # - name: Build Vue
      #   run: |
      #     cd src
      #     npm ci
      #     npm run build -- nvdev
      # - name: Deploy dist to oss
      #   env:
      #     Endpoint: oss-accelerate.aliyuncs.com
      #     Upload_dir: src/dist
      #     Bucket_name: nuvision-web-dev
      #     OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
      #     OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
      #   run: |
      #     pip install oss2==2.10.0
      #     python tools/upload-oss.py $Upload_dir $Bucket_name $OSS_KEY_ID $OSS_KEY_SECRET $Endpoint
      # - name: notify with email
      #   uses: dawidd6/action-send-mail@v2
      #   with:
      #     server_address: smtp.qq.com
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Github Actions job result
      #     # Literal body:
      #     body: ${{github.repository}} dev Build and Test successfully!
      #     # Read file contents as body:
      #     # body: file://README.md
      #     to: ten.wong@nuvision.io, hunk@nuvision.io, yangwenhong@nuvision.io, xiaochangpeng@nuvision.io
      #     from: notification # <user@example.com>
      #     # Optional content type (defaults to text/plain):
      #     content_type: text/html
      #     # Optional attachments:
      #     # attachments: attachments.zip,git.diff,./dist/static/main.js
